version: '4.34.2'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "parking"
      POSTGRES_USER: "user1"
      POSTGRES_PASSWORD: "parkingpassword"
    ports:
      - "5431:5432"

  postgres_db2:
    image: postgres:16
    environment:
      POSTGRES_DB: "booking"
      POSTGRES_USER: "user2"
      POSTGRES_PASSWORD: "bookingpassword"
    ports:
      - "5433:5432" 
 
  postgres_db3:
    image: postgres:16
    environment:
      POSTGRES_DB: "Identity"
      POSTGRES_USER: "user3"
      POSTGRES_PASSWORD: "identitypassword"
    ports:
      - "5434:5432" 
    
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq

  postgres_db4_keys:
    image: postgres:16
    environment:
      POSTGRES_DB: "ProtectionKeys"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "key"
    ports:
      - "5435:5432"

volumes:
  postgres:
  postgres_db2:
  postgres_db3:
  rabbitmqdata:

